[package]
authors = ["Apollo Devs"]
description = "Helper library for interacting with Cosmos dexes"
edition = "2018"
license = "GPL-3.0-or-later"
name = "cw-dex"
repository = "https://github.com/apollodao/cw-dex"
version = "0.0.1"

[features]
default = ["osmosis"]
osmosis = []

[dependencies]
apollo-proto-rust = {branch = "master", git = "https://github.com/apollodao/apollo-proto-rust"}
cosmwasm-std = {version = "1.0", features = ["stargate"]}
# cw-asset = "2.1.0"
cw-asset = "^2.3.0"
# cw-token = { path = "../../../cw-token" }
cw-storage-plus = "0.13"
cw-token = { git = "https://github.com/apollodao/cw-token.git" }
cw-utils = "0.13"
cw20 = "0.13"
cw20-base = "0.13"
osmo-bindings = "0.5.1"
schemars = "0.8.1"
serde = {version = "1.0.103", default-features = false, features = ["derive"]}
thiserror = {version = "1.0.31"}
