[package]
name = "cw-dex"
description = "Helper library for interacting with Cosmos dexes"
version = "0.0.1"
authors = ["Apollo Devs"]
edition = "2018"
license = "GPL-3.0-or-later"
repository = "https://github.com/mars-protocol/cw-asset"

[features]
default = ["osmosis"]
osmosis = []

[dependencies]
apollo-proto-rust = { branch = "master", git = "https://github.com/apollodao/apollo-proto-rust" }
cosmwasm-std = { version="1.0", features = ["stargate"] }
cw20 = "0.13"
cw20-base = "0.13"
cw-storage-plus = "0.13"
schemars = "0.8.1"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
thiserror = {version = "1.0.31"}
cw-asset = { git = "https://github.com/apollodao/cw-asset.git", branch = "dev/tokenideas"}
