[workspace]
members = ["cw-dex", "test-contract", "test-helpers"]
resolver = "2"

[workspace.package]
authors       = ["Apollo Devs <shared@apollo.farm>"]
edition       = "2021"
license       = "MPL-2.0"
homepage      = "https://apollo.farm"
repository    = "https://github.com/apollodao/cw-dex"
documentation = "https://docs.rs/cw-dex"
keywords      = ["blockchain", "cosmos", "cosmwasm"]
rust-version  = "1.64.0"

[workspace.dependencies]
cosmwasm-schema = "1.1.3"
cosmwasm-std = "1.1.3"
cosmwasm-storage = "1.1.3"
cw-storage-plus = "0.15.1"
cw2 = "0.15.1"
schemars = "0.8.10"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }
cw-asset = { git = "https://github.com/apollodao/cw-asset.git", rev = "057fb193013ad4adfc25063b99960972d1d208bc" }
# cw-asset = { path = "../cw-asset" }
osmosis-testing = { path = "../osmosis-rust/packages/osmosis-testing/" }
osmosis-std = { path = "../osmosis-rust/packages/osmosis-std/" }
cw-it = { path = "../cw-it" }

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
opt-level        = 3
overflow-checks  = true
rpath            = false