[package]
authors = ["Apollo Devs"]
description = "Helper library for interacting with Cosmos dexes"
edition = "2021"
license = "GPL-3.0-or-later"
name = "cw-dex"
repository = "https://github.com/apollodao/cw-dex"
version = "0.0.1"

[features]
default = ["osmosis"]
osmosis = []

[dependencies]
osmosis-std = { git = "https://github.com/apollodao/osmosis-rust.git", branch = "feat/msg-force-unlock-type" }
cosmwasm-schema = "1.1.0"
cosmwasm-std = {version = "1.1.0", features = ["stargate"]}
cw-asset = "2.3.0"
cw-storage-plus = "0.15"
cw-utils = "0.16"
cw20 = "0.15"
cw20-base = "0.15"
num-bigint = "0.4"
num-rational = "0.4"
num-traits = "0.2.15"
osmo-bindings = "0.5.1"
schemars = "0.8.8"
serde = {version = "1.0.137", default-features = false, features = ["derive"]}
thiserror = {version = "1.0.31"}
prost = {version = "0.11.0", default-features = false, features = ["prost-derive"]}

# Junoswap
wasmswap = { git = "https://github.com/Wasmswap/wasmswap-contracts.git", tag = "v1.1.0-beta", features = ["library"] }
cw20-0_10_3 = { package = "cw20", version = "0.10.3" }
cw20-stake = { git = "https://github.com/DA0-DA0/dao-contracts" } # TODO: what version?
stake-cw20-external-rewards = { git = "https://github.com/DA0-DA0/dao-contracts", features = ["library"] } # TODO: what version?
cw-utils-0_13_4 = { package = "cw-utils", version = "0.13.4" }
