[package]
authors = ["Apollo Devs"]
description = "Helper library for interacting with Cosmos dexes"
edition = "2021"
license = "MPL-2.0"
name = "cw-dex"
repository = "https://github.com/apollodao/cw-dex"
version = "0.0.1"

[features]
default = []
osmosis = ["dep:osmosis-std"]
astroport = ["dep:uint", "cw-asset/astroport"]
junoswap = ["dep:wasmswap","dep:stake-cw20", "dep:cw20-0_10_3"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
cosmwasm-schema = "1.1.0"
cosmwasm-std = {version = "1.1.0", features = ["stargate"]}
cw-asset = { git = "https://github.com/apollodao/cw-asset.git", rev = "5e51773da42ef82faa67576454e8c4b0971097f2" }
cw-storage-plus = "0.16"
cw-utils-0-11 = { package = "cw-utils", version = "0.11" }
cw-utils = "0.16"
cw20 = "0.16"
thiserror = {version = "1.0.31"}
apollo-utils = { git = "https://github.com/apollodao/apollo-utils.git", rev = "dd3da52653d3dc350b20b46f363ebcfdcd64aa27" }


# Osmosis
osmosis-std = { git = "https://github.com/apollodao/osmosis-rust", rev = "52ca8eaa4b2926fea01a68f4d7e7253ad29d88b3", optional = true }

# Astroport
uint = {version = "0.9.3", optional = true}

# Junoswap
wasmswap = { git = "https://github.com/Wasmswap/wasmswap-contracts.git", tag = "v1.1.0-beta", features = ["library"], optional = true }
cw20-0_10_3 = { package = "cw20", version = "0.10.3", optional = true } # We must import this version separately since it is what wasmswap uses.
stake-cw20 = { version = "0.2", features = ["library"], optional = true }
# stake-cw20-external-rewards = { git = "https://github.com/DA0-DA0/dao-contracts", features = ["library"] }

# [build-dependencies]
# integration-tests-config = { branch = "develop-cw-dex", git = "https://github.com/apollodao/cw-integration-tests.git" }

test-case = "2.2.2"

[dev-dependencies]
# Integration tests
#build-artifacts = { branch = "develop-cw-dex", git = "https://github.com/apollodao/cw-integration-tests.git" }
integration-tests-core = { branch = "develop-cw-dex", git = "https://github.com/apollodao/cw-integration-tests.git" }
integration-tests-config = { branch = "develop-cw-dex", git = "https://github.com/apollodao/cw-integration-tests.git" }
cw-dex-test = { branch = "develop-cw-dex", git = "https://github.com/apollodao/cw-integration-tests.git" }
testcontainers = { version = "0.14.0", features = ["experimental"] }
cosmrs = { version = "0.9.0", features = ["cosmwasm"] }

# mocking integrations tests
cw-multi-test = "0.16.0"

# multiple-testing
test-case = "2.2.2"

