[package]
authors = ["Apollo Devs"]
description = "Helper library for interacting with Cosmos dexes"
edition = "2018"
license = "GPL-3.0-or-later"
name = "cw-dex"
repository = "https://github.com/apollodao/cw-dex"
version = "0.0.1"

[features]
default = ["osmosis"]
osmosis = []

[dependencies]
cosmwasm-std = {version = "1.1.0", features = ["stargate"]}
cosmwasm-schema = "1.1.0"
serde = {version = "1.0.137", default-features = false, features = ["derive"]}
thiserror = {version = "1.0.31"}
schemars = "0.8.8"
cw-storage-plus = "0.15"
cw-asset = "2.3.0"
apollo-proto-rust = {git = "https://github.com/apollodao/apollo-proto-rust", branch = "dev/cosmwasm-1.1"}
cw-token = { git = "https://github.com/apollodao/cw-token.git", branch = "dev/cosmwasm-1.1" }
cw-utils = "0.15"
cw20 = "0.15"
cw20-base = "0.15"
osmo-bindings = "0.5.1"
